pnxtech/hydra-router

.travis.yml
=> Travis CI Integration 

config/sample-config.json, hydra-router.js, package.json
Does not load risingStack trace unless flag is set to true on config.json
=> Support for RisingStack Trace

package.json, servicerouter.js
toRoute was already defined, so the second let was causing it to be undefined higher up within that let's scope
=> No ws service fix

hydra-router.js, package.json
=> Switch to uws for websockets

config/sample-config.json, hydra-router.js, package.json, servicerouter.js
To turn on, change the config `debugLogging` from false to true.
=> Support for conditional logging

hydra-router.js, package.json
=> Improved process exit handling

docker-build.sh, hydra-router.js, package.json, public/index.html
* Improved process cleanup handling
* identify hydra-router on dashboard
* shell script for building docker container also pushes to repo
=> Improved error handling and deployment

package.json
and fwsp-server-response": "2.2.6
=> Updated hydra core to 1.1.2

package.json
=> Update fwsp-logger 0.1.5

hydra-router.js, package.json, servicerouter.js
This clears dead services so they don't show up on the dashboard.
=> New /v1/router/clear command

package.json, servicerouter.js
Changing content-length header to count bytes instead of character length.
=> Fix content-length character counting bug

servicerouter.js
* Fix for ill-formed jsdoc block
* Move wsClients object into class
* Use built-in ServerResponse consts
* Small code cleanup
=> Code cleanup

.dockerignore, config/sample-config.json, hydra-router.js, package-lock.json, package.json, public/index.html, servicerouter.js
Support for debug module
Improved error catching
Support for hydra 1.4.11 hostname output
update to hydra 1.4.11 and fwsp-logger 0.3.0 and ws 3.1.0
=> Recent improvements

Dockerfile, hydra-router.js, package-lock.json, package.json, servicerouter.js
* Improved health check handling, moved health endpoint to router API
* Added start-period for docker healthcheck
* Reordered health statement to top of dockerfile.
=> Healthcheck updates for service and docker container

Dockerfile, hydra-router.js, package-lock.json, package.json, servicerouter.js
* Added start-period for docker healthcheck 
* Reordered health statement to top of dockerfile
* Output detected network interfaces
* Enable websocket calls to query router
=> Improvements for Docker use and Websockets

Dockerfile, hydra-router.js, package-lock.json, package.json
* Shorten healthcheck interval
* Update to hydra 1.4.18
* Support for IP binding via hydra 1.4.16
=> Support for IP binding

package-lock.json, package.json, servicerouter.js
- Updating web socket message handler to keep headers intact. 
- `Package-lock.json` did not work on my machine (ton of missing dependency error). I deleted and did a new `npm install` re-generating the lock file.
=> Fix UMF dropped fields

package-lock.json, package.json, servicerouter.js
Fixing routing error caused by PR-146.
=> Fix WS UMF Message Routing Error

package-lock.json, package.json, public/index.html
and a bit of cleanup in prep for stats screen.
=> Dashboard: fix for missing log screen

hydra-router.js, lib/servicerouter.js, package-lock.json, package.json
Also upgraded to the latest release on 3.x branch.
=> Improved ws error handling. 
